spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.145/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.31.145
server:
  servlet:
    context-path: /sell


wechat:
  myAppId: wx965a634423c4d40e
  myAppSecret: fe4ed99d0275ed511a76695e064c90b4
logging:
  level:
    com.chen.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml



